# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    [r"D:/Deng/can_test/python_executor/app.py"],
    pathex=[r"D:/Deng/can_test/python_executor"],
    binaries=[],
    datas=[
        (r"D:/Deng/can_test/python_executor/web/templates", "web/templates"),
        (r"D:/Deng/can_test/python_executor/web/static", "web/static"),
    ],
    hiddenimports=[
        'webview',
        'webview.platforms.winforms',
        'webview.http',
        'webview.util',
        'webview.screen',
        'webview.window',
        'webview.localization',
        'flask',
        'werkzeug',
        'werkzeug.routing',
        'jinja2',
        'jinja2.ext',
        'markupsafe',
        'itsdangerous',
        'click',
        'psutil',
        'psutil._pswindows',
        'websockets',
        'websockets.legacy',
        'websockets.legacy.client',
        'win32com',
        'win32com.client',
        'win32com.gen_py',
        'pythoncom',
        'config.settings',
        'core.status_monitor',
        'utils.logger',
        'web.server',
        'clr',
        'clr_loader',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'tkinter',
        'unittest',
        'pytest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='测试执行器',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
    version=r"D:/Deng/can_test/python_executor/build/version.txt",
)
